### ISSUE TITLE
TRelativePosUI不存在

### ISSUE THREAD

**Issue by acekingke** [duilib/duilib#10]
DuiDesigner 无法编译，
error C2039: “TRelativePosUI”: 不是“DuiLib”的成员。

**Comment by huangyt** [comment]
我也遇到了这个问题，VS2013。

**Comment by wangchyz** [comment]
库的代码改了，设计器还没有同步更新，估计要晚一段时间了，如果谁修改了，可以提交patch过来

**Comment by wangchyz** [comment]
库的代码改了，设计器还没有同步更新，估计要晚一段时间了，如果谁修改了，可以提交patch过来

**Comment by yongplus** [comment]
大概什么时候能解决呢

**Comment by sorawa** [comment]
这个问题什么时候能解决啊~

**Comment by gxt467138** [comment]
可用先用原来的设计器，原来的设计器还是可以继续用的。

**Comment by Nokecy** [comment]
原来的设计器在哪里有 。。。。

**Comment by xingzhe826** [comment]
耐心等待吧

**Comment by 839687571** [comment]
先用这个exe吧. 也是网上找的.
http://share.weiyun.com/5d99f6d2d0ed8e5f9a5ab62522ea7fbe
