### ISSUE TITLE
如何使用图片实现窗口阴影效果？

### ISSUE THREAD

**Issue by nmgwddj** [duilib/duilib#102]
我看到 duilib 的代码中已经集成了 `CWndShadow` 类，在提供的 test1 例子中也写了一个使用图片做阴影的例子。可移植到我的程序中时，就没有效果了，我的代码是这样写的。

```
LRESULT CMainFrameWnd::OnCreate(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
    __super::OnCreate(uMsg, wParam, lParam, bHandled);

    CWndShadow::Initialize(m_PaintManager.GetInstance());
    m_pWndShadow = new CWndShadow;
    m_pWndShadow->Create(m_hWnd);

#if 0
    RECT rcCorner = { 5,5,5,5 };
    RECT rcHoleOffset = { 0,0,0,0 };
    m_pWndShadow->SetImage(_T("bg_main_shadow.png"), rcCorner, rcHoleOffset);
#else
    m_pWndShadow->SetDarkness(80);
    m_pWndShadow->SetSize(4);
    m_pWndShadow->SetPosition(0, 0);
#endif

    return 0;
}
```

`CMainFrameWnd` 继承于 `WindowImplBase` 类，其中使用 `SetSize` 方法并在 xml 中增加 `roundcorner` 描述，是可以让窗口显示阴影的，可当使用 SetImage 时就没有效果了，请问这是什么原因，要如何处理？

**Comment by wangchyz** [comment]
CWndShadow::Initialize(hInstance);
这个调用过了吗

**Comment by JackLongBow** [comment]
我是用了两个窗口，一个窗口使用layeredwindow实现半透明阴影，另一个就是主窗口了。

**Comment by juhuaguai** [comment]
@nmgwddj 非常简单，设置window标签的layeredimage属性，然后找个带阴影的图片就好了。

**Comment by nmgwddj** [comment]
@juhuaguai 感谢你的回复，暂时关闭。

**Comment by dtamade** [comment]
layeredimage 标签会存在很多问题(比如 最大化后 窗体面积等),所以正经的做阴影还是要用 CWndShadow.
