### ISSUE TITLE
TreeView动态添加子节点，文本却没有显示

### ISSUE THREAD

**Issue by twithg** [duilib/duilib#103]
XML文件中定义了TreeView:
`<TreeView name="Tree1">
	<TreeNode  text="1" name="Node1" >
		<TreeNode text="1-1" />
		<TreeNode text="1-2" />
	</TreeNode>
</TreeView>`
想在代码中( InitWindow() ) 动态添加一个TreeNode，能添加成功，但是没有显示TreeNode的Text内容，请问是什么原因？
InitWindow的代码如下：
`CTreeViewUI* pTree = static_cast<CTreeViewUI*>m_PaintManager.FindControl(_T("Tree1")));
	if (pTree)
	{
		CTreeNodeUI* pNode = new CTreeNodeUI;
		pTree->Add(pNode);
		pNode->SetText(_T("node"));
	}`

**Comment by twithg** [comment]
已经知道原因了，对于TreeNode，要用 SetItemText才行；为什么SetText不行，这还不清楚求大神解答

**Comment by wangchyz** [comment]
tree的实现不是很好，等空的时间会重新实现一个

2016-10-18 14:28 GMT+08:00 twithg <notifications@github.com>:
