### ISSUE TITLE
CRichEditUI 响应 return 回车消息

### ISSUE THREAD

**Issue by tazm** [duilib/duilib#109]
UIRichEdit.cpp 第1734行 
是否应该有 if( !m_bWantReturn || (::GetKeyState(VK_CONTROL) < 0 && !m_bWantCtrlReturn) ) {
改为    if( m_bWantReturn || (::GetKeyState(VK_CONTROL) < 0 && m_bWantCtrlReturn) ) {

当 m_bWantReturn （m_bWantCtrlReturn）为true是代表可以 发送 return 消息，而不是为false时才发送。

**Comment by juhuaguai** [comment]
@tazm 原代码应该没问题。看完整代码，当m_bWantReturn为true时，return消息被发送给richedit，m_bWantReturn为false时，SendNotify出来然后返回，return消息没有发送给richedit。根据wantreturn属性的描述，是指richedit控件是否接受return按键消息。因此为true时消息被发送给richedit并没有问题。官方此处代码没有问题。
