### ISSUE TITLE
英文环境乱码问题

### ISSUE THREAD

**Issue by chigogithub** [duilib/duilib#110]
由于文件格式保持是默认的ANSI编码，在英文(非中文系统)的开发环境下面，编译出来的二进制文件是乱码，并且所有源码中文注释等都是乱码，建议对源码文件使用UTF-8编码，谢谢

**Comment by wangchyz** [comment]
实际上,ⅴs对utf-8支持不太好,经常有编译错误。最好还是把中文干掉

**Comment by chigogithub** [comment]
好吧，不过我本地的VS设置UTF-8倒从来没有出现过问题，目前我用这个库，都是先用NotePad++打开所有带中文的代码文件，然后转换成UTF-8格式，不过还好，就是以后代码库每次都同步更新的话，很蛋疼。谢谢回复，thanks
