### ISSUE TITLE
Combo的滚动条如何显示？

### ISSUE THREAD

**Issue by twithg** [duilib/duilib#111]
使用Combo控件时，发现点击箭头后，下拉列表中没有显示滚动条，同窗口中List可以显示滚动条，这是一个bug（Combo就不能显示滚动条）还是使用方法不对？

**Comment by juhuaguai** [comment]
@twithg 这确实是一个bug，我在个人的仓库中进行了修复。你可以搜索juhuaguai/duilib来查看。个人水平有限，仅供参考。
@wangchyz 非常抱歉我拿官方代码重新建了个仓库而不是由官方fork出来。随后有空，我将fork一份官方的代码来将我个人修复的一些问题pull requests到官方仓库。

**Comment by wangchyz** [comment]
设置全局default的滚动条属性或者设置dropbox属性
