### ISSUE TITLE
layeredimage属性加入corner，拖动窗口大小后出现问题。

### ISSUE THREAD

**Issue by shithappens2016** [duilib/duilib#113]
笔者用一张png做窗口周围阴影。
layeredimage 后加上corner设置。
无论怎么设置corner大小，都出现绘制问题。
具体请看图。
![layeredimage1](https://cloud.githubusercontent.com/assets/13523412/20678854/472e1900-b5d3-11e6-9ded-9390df8587e2.jpg)
![layeredimage2](https://cloud.githubusercontent.com/assets/13523412/20678866/53861734-b5d3-11e6-9aae-b6174d1a1eec.jpg)
![layeredimage3](https://cloud.githubusercontent.com/assets/13523412/20678870/5854bc98-b5d3-11e6-9914-f6860663fad1.jpg)
最后附上作为阴影的png：
![bkg](https://cloud.githubusercontent.com/assets/13523412/20678912/8071d24c-b5d3-11e6-9c07-acb9e96db1a1.png)

**Comment by juhuaguai** [comment]
@shithappens2016 你好，我这边测试并没有观察到这个现象，能否把你的demo的exe分享给我一份，仅当学习使用。邮箱934130966@qq.com 谢谢！

**Comment by wangchyz** [comment]
有png做背景为什么还需要设corner

**Comment by shithappens2016** [comment]
@wangchyz
这个png仅用作窗口周围的阴影，即只需4个边，故设置corner。比如迅雷的bolt就是这样作阴影的，效果很好。
其实，如果不设置corner，拖动窗口大小后问题会更严重：一来，图片被简单全图拉伸，导致阴影变形；二来，如上所说的空隙依旧出现，而且更严重。

**Comment by Justysxh** [comment]
因为windows窗口,, 如果非层叠窗口是做不到透明的. 这时要实现圆角窗口, 那么必然只能做像素裁剪, 那么"锯齿" 现象就出来了, 而你的PNG实现圆角是依赖透明才那么平滑.   
然而悲剧的是duilib库的容器的窗口就是非层叠窗口,  这么PNG和像素裁剪加在一起, 自然被裁剪成你那种难看的样子(黑色背景或者其它有色背景填充). 原来PNG半透明的部分被有色非透明组合叠加,就变成了那个丑样了.

**Comment by shithappens2016** [comment]
@Justysxh 
抱歉，我的那张阴影png图片四角上没阴影，可能让你产生了误解。

设置corner是以九宫格法切割那张png并贴图到窗口，这样可以防止边角拉伸变形，并不是用来作圆角窗口的。

**Comment by shithappens2016** [comment]
感谢大家的关注。
特别感谢@juhuaguai 的提醒。 

经过反复调试，最后发现是图片问题。由于分割处边界处有多余空白，所以窗口缩放时，这块空白被缩放，形成空隙。

再次谢谢大家。
