### ISSUE TITLE
RichEdit控件怎么给关键字高亮显示？

### ISSUE THREAD

**Issue by sheldon-** [duilib/duilib#114]

**Comment by juhuaguai** [comment]
@sheldon- 如果只是想选中，那么有接口很简单；如果是想改变字体字号等，可以搜索charformat相关；如果想加链接，可以搜EN_LINK相关；如果是其他需求，那么直接搜需求吧，我知道的也不多。

**Comment by sheldon-** [comment]
就是只给文本段中的两个字改变颜色

**Comment by wangchyz** [comment]
duilib中的richedit是系统richedit，和mfc或wtl中的用法类似，你可以搜一下mfc是怎么处理的
