### ISSUE TITLE
RichEdit下，垂直滚动条，不能正确退出Hot状态。

### ISSUE THREAD

**Issue by shithappens2016** [duilib/duilib#119]
RichEdit下的垂直滚动条，当鼠标指针从滚动条自身移动到RichEdit内时，滚动条无法退出Hot状态。

我自己翻看了代码，对结构不够熟悉，找不到缘故，请大家帮助。

**Comment by juhuaguai** [comment]
@shithappens2016 这个bug我已经知道，richedit中不仅仅是滚动条的Hot有问题，其他控件比如button在hot状态时，鼠标直接移到richedit中，button的hot状态也是无法正确退出的。实在抱歉现在手头事情比较多，没有时间看。期待有大神的指导。。。持续关注中

**Comment by CCwant** [comment]
这个问题我已经修复，详情请查看http://blog.csdn.net/cc_want/article/details/60956612

**Comment by shithappens2016** [comment]
@CCwant
感谢小伙伴的热心解答。
