### ISSUE TITLE
win8 Win10系统下，CRichEditUI输入汉字、显示汉字时乱码

### ISSUE THREAD

**Issue by szstorms** [duilib/duilib#134]
主要是因为CRichEditUI使用了msftedit.dll引起：
BOOL CTxtWinHost::Init(CRichEditUI *re, const CREATESTRUCT *pcs){
 ......
 PCreateTextServices TextServicesProc;
 HMODULE hmod = LoadLibrary(_T("msftedit.dll"));
 ......
}
将“msftedit.dll”改为”riched20.dll“可解决，请合并代码。

**Comment by wangchyz** [comment]
这个问题网上有篇文章谈到过，最好的办法是用unicode发布程序。
msftedit.dll的作用是加载最新版本的richedxx.dll。各个版本的richedit实现有区别，导致出现这个问题。riched20.dll的版本比较老，有些windows版本也未必有这个dll，如果你有需要可以改成这个，但是不太适合合并到主干代码里面

**Comment by szstorms** [comment]
从xp到win10都有这个riched20.dll。。。

**Comment by wangchyz** [comment]
好吧，那我搞错了，不过ms的各个版本richedit兼容性确实是个问题，我看很多pc应用都自带一个richedit20.dll。
还是用unicode版本吧
