### ISSUE TITLE
当前主干dui编译爆出很多错误

### ISSUE THREAD

**Issue by shantj** [duilib/duilib#135]
![image](https://cloud.githubusercontent.com/assets/9815535/23306352/2dfa27b2-fade-11e6-9194-51ff979e5a92.png)

编译器 vs2008、vs2015都这样，是不是少什么文件没有传啊。。。。。

**Comment by shantj** [comment]
@wangchyz 主干编译报错。。。。

**Comment by wangchyz** [comment]
这个你耐心点找下原因或者请旁边的同事同学看看，应该是很好解决的
