### ISSUE TITLE
当window 的 roundcorner 没有设置的时候 CWndShadow 无法显示

### ISSUE THREAD

**Issue by ebel2000** [duilib/duilib#136]
如题，xml里面的window 如果不设置圆角，则阴影无法显示

**Comment by wangchyz** [comment]
是不是ws_popup类型的窗口

**Comment by ebel2000** [comment]
UI_WNDSTYLE_DIALOG 和 UI_WNDSTYLE_FRAME 都存在这样的问题，你测试下roundcorner去掉就会显示不出来阴影
<Window size="602,480" caption="0,0,0,375" roundcorner="4,4">

**Comment by wangchyz** [comment]
我现在项目试过是好的，和roundcorner无关
你用spy查看一下阴影窗口是不是没有ws_visible属性，如果没有，你在创建阴影窗口之后，设置一下这个属性试试，这个好像是wndshadow的bug

**Comment by ebel2000** [comment]
窗口可以检测到，而且SetImage都是可以看到的，就是使用颜色设置不可以，加上roundcorner问题解决了

**Comment by dtamade** [comment]
的确存在这个问题
