### ISSUE TITLE
Layered=true时，在CRichEditUI中"文本被选中的位置"，点右键，无法收到DUI_MSGTYPE_MENU消息；文本不选中的位置则正常。

### ISSUE THREAD

**Issue by shithappens2016** [duilib/duilib#137]
**有2个关于CRichEditUI事情。**

**首先：**
说明下，窗口是Layered=true的。

**第一：**
就是标题里说的。CRichEditUI中，文本被选中的位置，点右键，就无法收到DUI_MSGTYPE_MENU消息。文本没有选中的位置点右键则正常收到DUI_MSGTYPE_MENU消息。

**第二：**
CRichEditUI中，全选或选择一部分文本后，插入光标不隐藏，还是在闪啊闪！

**配图：**
![bug](https://cloud.githubusercontent.com/assets/13523412/23509173/db05ca6e-ff8f-11e6-8e8a-fd50006de698.jpg)

@juhuaguai 
@wangchyz 
@672399809

**Comment by 672399809** [comment]
可以参照下duilib中CRichEditUI的实现，windowless的RichEdit，ITestHost中的消息都是通过CRichEditUI的消息传递进来的，应该是其中漏了部分消息的传递，比如WM_SETFOCUS,WM_KILLFOCUS

**Comment by shithappens2016** [comment]
@672399809 我说的就是CRichEditUI的问题，并不是我重写一个windowless的RichEdit出现问题。不好意思，前面我没写清楚，导致了误解。请问，你那里能否重现这2个问题？

**Comment by 672399809** [comment]
也有这现象，可以跟一下UIManager中的MessageHandler，DUI_MSGTYPE_MENU是通过WM_CONTEXTMENU的消息响应分发过来的，其中有个判断 if( m_pEventClick == NULL ) break;

而这个m_pEventClick 需要在WM_RBUTTONDOWN时被设置才有，选中文本后点击右键，RichEditUI标记为bWasHandled，所以没有进入默认的处理，导致响应WM_CONTEXTMENU时break了

**Comment by wangchyz** [comment]
这个消息被richedit处理了，可以继承IRichEditOleCallback接口，实现GetContextMenu，在这个方法中弹出菜单。
然后使用TxSendMessage(EM_SETOLECALLBACK, ...)方法设置richedit的olecallback

**Comment by shithappens2016** [comment]
感谢作者和672399809的热心解答。第一个问题圆满解决。
@672399809 
@wangchyz 

第二个问题，任然存在，不知道两位能否给点建议，谢谢。

**Comment by captainwong** [comment]
第一个问题是如何解决的呢？我没找到IRichEditOleCallback的定义
