### ISSUE TITLE
2.0版本编译时提示很多文件找不到

### ISSUE THREAD

**Issue by oskycar** [duilib/duilib#146]
编译时提示以下文件找不到：
UIlib.h ： fatal error C1083: 无法打开包括文件: “../Global/ddll.h”: No such file or directory
 UIDefine.h:  fatal error C1083: 无法打开包括文件: “Utils/BufferPtr.h”: No such file or directory

在源码目录里面的确找不到这两个文件。注释掉include这两个文件的代码，会报更多的类型未定义错误

**Comment by daviyang35** [comment]
这些内容牵扯到一些公司的商业代码，无法公开。
不过内容绝大部分是Win32 API的封装实现，可以替换掉实现或者直接用Win32 API

**Comment by daviyang35** [comment]
我有可能会将这部分实现重写，但是不确定，与公司的需求和计划有关。
如果有人有实现，欢迎PR
