### ISSUE TITLE
在vs2017上没法编译

### ISSUE THREAD

**Issue by leitwolf** [duilib/duilib#148]
最新版win10，vs2017也是刚更新的。
xp c++ support也已经安装了。
感觉是没有设置对winsdk，但属性配置已又没有得选择。

**Comment by leitwolf** [comment]
解决了，还要添加C++ ALT支持。

**Comment by e-hai** [comment]
@leitwolf 可以详细说下编译的步骤吗？

**Comment by leitwolf** [comment]
就是安装时勾选有ALT库。

**Comment by CSTOMJason** [comment]
@leitwolf 勾选了ATL库还是报错，你能将你的编译过程截个图写篇博客吗关于vs2017 编译duilib

**Comment by leitwolf** [comment]
@CSTOMJason 不好意思，当时只是有兴趣试一试这个库，现在早已不弄了，开发环境也没有了。帮不了你了，抱歉！
