### ISSUE TITLE
RichEdit 装入超过 5000行(\r\n)  文本后，滚动条的滚动会出错，拉到最底，文本却停留在中间。

### ISSUE THREAD

**Issue by shithappens2016** [duilib/duilib#149]
RichEdit 装入超过5000行(\r\n)  文本后，滚动条的滚动会出错，拉到最底，文本却停留在中间。
看了好久，找不出问题所在，请大家帮助下。
@wangchyz

**Comment by juhuaguai** [comment]
@shithappens2016 这个问题我看了代码调试了一下，也找出了问题所在，可惜对于修复目前无能为力，抱歉了。问题在于TxSetScrollRange这个函数(搜索代码能找到)：
当richedit的文本内容的滚动条范围改变，调用该函数。其中nMaxPos的表示最大滚动位置（Maximum scrolling position），由于MS的某些原因，这个值最大为65535。所以，当文本内容过多时滚动范围超出了65535时，这个值仍然是65535，从而引起CScrollBarUI里面的滚动范围上限也变为了65535，引发了滚动不到真正的内容底部的问题。
