### ISSUE TITLE
XML Window 设置bktrans="true" alpha="200均无效

### ISSUE THREAD

**Issue by AIrSkycc** [duilib/duilib#150]
如题，窗口还是为黑色无法透明。

**Comment by AIrSkycc** [comment]
![1111](https://user-images.githubusercontent.com/8086189/32875421-e20c48c4-cad2-11e7-992b-df4cca3f6e42.png)

**Comment by juhuaguai** [comment]
layeredimage或者opacity，bktrans和alpha都是已经废弃的属性。 @AIrSkycc

**Comment by AIrSkycc** [comment]
请问是否有更新后的XML属性列表？感谢！

@juhuaguai
