### ISSUE TITLE
RBG 误用，颜色格式和代码之间存在设计问题！

### ISSUE THREAD

**Issue by UMU618** [duilib/duilib#159]
代码里大量的误用 RGB 这个宏

请注意这个宏是这样定义的：

#define RGB(r,g,b)          ((COLORREF)(((BYTE)(r)|((WORD)((BYTE)(g))<<8))|(((DWORD)(BYTE)(b))<<16)))

但本项目是这样用的：

lg.lopnColor = RGB(GetBValue(dwPenColor), GetGValue(dwPenColor), GetRValue(dwPenColor));

2013 年就发现这个 bug，至今都没改啊？

**Comment by UMU618** [comment]
@k1988 不存在使用错误的说法，我可以用现有的错误设计，只是我不想用，和标准或者说大部分软件保持一样，所以我自己全部改过了。

**Comment by UMU618** [comment]
@k1988 并没有使用错误，我一开始都是照原版来的，用了一段时间，发现坑很大，基于目前代码和 HTML 的标准，我把 XML 里的颜色都改为 RGBA 格式了。我要讨论的是设计合理性，而不是理解问题，谢谢。

<body bgcolor="#FF0000"></body> 这个打开是红色
<body bgcolor="#FF000000"></body> 这个打开还是红色
<body bgcolor="#00FF0000"></body> 这个打开是绿色

所以，个人认为 RGB 要扩展到加 Alpha 通道，应该是 RGBA。作者用 ARGB 所以才会出现那么怪异的代码……如果非要这么用，起码也加个转换宏。

**Comment by UMU618** [comment]
我改后的格式是这样的：
按 RBG 宏，颜色格式是这样的 32 位数字：0x00bbggrr，在小尾字节序内存里是 0xrr 0xgg 0xbb 0x00
直接利用最高（最后）字节就是 0xaabbggrr，内存：0xrr 0xgg 0xbb 0xaa
eg: 0xFF0000FF 表示红色，0xFFFF0000 表示蓝色。

**Comment by wangchyz** [comment]
argb是同行的一种做法，如果说困恼，就是不该偷懒用了RGB和GetBValue
