### ISSUE TITLE
webbrowser控件自定义右键菜单栏如何实现

### ISSUE THREAD

**Issue by wangzhechn** [duilib/duilib#166]
如题，请问有大佬实现过的吗

**Comment by juhuaguai** [comment]
@wangzhechn https://bbs.csdn.net/topics/390476642?page=1 网上找的，可以参考下。我没有实现过。

**Comment by daviyang35** [comment]
楼上为正解

**Comment by wangzhechn** [comment]
这个是可以覆盖原生的菜单，但是在哪里去做事件响应呢
