### ISSUE TITLE
DUILIB 是否有规划在跨平台方面做扩展，比如在linux 和 OSX下使用

### ISSUE THREAD

**Issue by meaningful** [duilib/duilib#178]
目前在控件的绘制方面目前是基于GDI+ 的控件绘制， 核心框架和原理比如消息机制是windows程序设计的部分。 

可配置化的界面是本框架的亮点 。 我想这个才是duilib最核心和有价值的地方。

如果想要跨平台， 可能框架会有较大的更改， 在界面的绘制方面可以考虑复用QT .  可以参考wxwidgets 这个项目。 

不知道贵项目组是否有考虑跨平台相关的事情， 如果有考虑，我愿意贡献一部分自己的力量，参与进来。 谢谢。

**Comment by progmboy** [comment]
目前只做了gtk移植的一些工作,还有很多方面没有弄完全.有兴趣可以看下https://github.com/duilib/gtkduilib.git

**Comment by daviyang35** [comment]
Qt本身就是跨平台的解决方案。而且Qt本身也有QML。已经没有duilib啥事儿了。
一个是lib，一个是foundation，两者的使用场景和定位就不同。
duilib可以做移植，如果三平台能够统一接口，那也是不错的解决方案。
目前没有明确的推进计划。
