### ISSUE TITLE
vs2017编译失败

### ISSUE THREAD

**Issue by 416207298** [duilib/duilib#201]
提示“无法找到v120_xp的生成工具“，请问这是vs的版本不兼容导致的吗？

**Comment by kefeng-wang** [comment]
修改项目属性即可，如下图：
![image](https://user-images.githubusercontent.com/18213586/64595533-ba1d5700-d3e4-11e9-8695-e2c8f127a697.png)

**Comment by 416207298** [comment]
> 修改项目属性即可，如下图：
> ![image](https://user-images.githubusercontent.com/18213586/64595533-ba1d5700-d3e4-11e9-8695-e2c8f127a697.png)

确实是因为这个原因！谢谢~
