### ISSUE TITLE
duilib版本号问题

### ISSUE THREAD

**Issue by v172744v** [duilib/duilib#208]
请问duilib有没有版本号一说，需要怎么查看版本号？如果只有源码要怎么查看呢？

**Comment by zhaokeli** [comment]
没有版本号一说，都是自己拉一份扩展自己的库

**Comment by v172744v** [comment]
没有版本号的话，事后如何知道自己获取的基础库是什么状态，更新都靠自己手动了吗？
还有客户可能会想知道开源库的版本信息，又如何解释这种情况好

**Comment by zhaokeli** [comment]
duilib只是开源代码，但并没有承诺维护这个代码，大家都可以自己拉一份在这个基础上进行修改，从而做为自己的基础库代码，自己可以打一个版本号然后开源到github上告诉客户你用的是哪个库的哪个版本就行啦。 。

**Comment by v172744v** [comment]
“那个库的哪个版本”我现在就是不知道这个，手上有一套源码，就是分不清楚这个。是自己定个版本号吗？要如何确定这个源码到底是哪个基础版扩展的？是否有方法？还是直接说是基础版的基础上扩展的比较合适

**Comment by daviyang35** [comment]
没有固定的发布周期与发布计划，所以版本号几乎无效。
你需要对比代码差异，结合人工审查来确定什么新什么旧
