### ISSUE TITLE
给出国内快速安装DuiLib的方法

### ISSUE THREAD

**Issue by ScSofts** [duilib/duilib#209]
下载这个包管理器
[https://gitee.com/gitnow/VCPM](https://gitee.com/gitnow/VCPM)
然后执行命令
`vcpm install duilib`
这个管理器由本人自己开发，使用国内Gitee镜像，速度异常快。自带Mini的Git

**Comment by ScSofts** [comment]
主要是vcpkg安装太慢了

**Comment by scorpion9111** [comment]
用你这个确实快

**Comment by JackBoosY** [comment]
@ScSofts 啥，那我做的vcpkg mirror是干嘛用的。
