### ISSUE TITLE
发现另一个好用的设计器完善的dui界面库'REDM'，有兴趣一起维护的吗？

### ISSUE THREAD

**Issue by halx99** [duilib/duilib#213]
https://github.com/simdsoft/REDM/issues/2

**Comment by KnIfER** [comment]
可有新功能，比如：dpi缩放、svg图片、android::LinearLayout权重控制大小、android::ListView虚表加载大数据、文本显示自适应高度、文本编辑自适应高度、多行文本自适应高度、多行文本居中？

**Comment by KnIfER** [comment]
设计器什么开发的，opengl？

**Comment by KnIfER** [comment]
文件编码不是unicode……
编译失败了

**Comment by KnIfER** [comment]
编辑器咋用，他说拖拽res文件夹，可是qqdemo中没有这个文件夹

**Comment by KnIfER** [comment]
不好玩

**Comment by KnIfER** [comment]
![image](https://user-images.githubusercontent.com/11593903/112460491-4cf0cd00-8da2-11eb-8974-79e9e6bfe065.png)

好坑啊

**Comment by KnIfER** [comment]
不如录个视频教程上传b站吧……那些动图太多了

**Comment by KnIfER** [comment]
qq demo 为什么这个样子……

![image](https://user-images.githubusercontent.com/11593903/112461567-634b5880-8da3-11eb-870c-e26d111ce1b5.png)

难道说不应该将源代码全部转换为unicode？有编译好的吗

**Comment by KnIfER** [comment]
1h : 从入门到放弃……

**Comment by halx99** [comment]
> ![image](https://user-images.githubusercontent.com/11593903/112460491-4cf0cd00-8da2-11eb-8974-79e9e6bfe065.png)
> 
> 好坑啊

ctrl+q切换到design视图

**Comment by halx99** [comment]
我最开始用也疑惑了很久，这操作，后面看看有空设计器交互优化下吧

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
