### ISSUE TITLE
Is there something similar to SetWindowText to work with duilib

### ISSUE THREAD

**Issue by itsho** [duilib/duilib#215]
Hello. 

First - this is an AMAZING project. kudus!.
Second - Is there anything similar/equivalent to `SetWindowText` or `WM_SETTEXT` that works on Applications created with `duilib`?

Thanks in advance! 😄 

Apologies for not writing in Chinese...

**Comment by daviyang35** [comment]
Text label have setText method.

**Comment by itsho** [comment]
Yes, I've seen that,
but my question is regarding a **different** process

**Comment by daviyang35** [comment]
Don't understand your intent.
Pls more describe what you want.

**Comment by itsho** [comment]
I have two EXE files:
1. app A written with duilib with 
2. app B written with **any** other UI infrastructure.

if app B wants to change the text in app A, naturally, it would use a WINAPI like `SetWindowText` or `WM_SETTEXT`
but, it would only work if app A is written with a _Windows_ GUI library like _MFC_ or _WinForms_.

now, that app A is using guilib, the mentioned WINAPI no longer works since app A does not have Handles to the inner parts.

so my question is:
is it possible to change any text in app A from app B like we use to do with the mentioned WINAPI?
the common case that I'm referring to is **translating** a running application to a different language.

Thank you very much in advance!

**Comment by daviyang35** [comment]
You can use the WM_COPYDATA message or other custom IPC protocol.
B send WM_COPYDATA message to A. payload describe target label control id and new message content.

**Comment by itsho** [comment]
Thank you.

Although very helpful, communication between two apps is not working well for my case - translating a **duilib** app without changing the first app code.

is there anything else I can do?

thanks again!

**Comment by daviyang35** [comment]
you mean that A is duilib app, B is any other implement app.
want change A's label and not modify A ?

**Comment by itsho** [comment]
yes. exactly. just like `SetWindowText` is working for old apps without changing them.

**Comment by daviyang35** [comment]
Can‘t do that.
Duilib is handleless framework. Can not change it's own control behavior with Window Message.
