### ISSUE TITLE
建议在 uilib.h中移除无关的头文件，减少依赖

### ISSUE THREAD

**Issue by horatii** [duilib/duilib#22]
建议在 uilib.h中移除无关的头文件，减少依赖。可以把duilib依赖的头文件移到stdafx中，在uilib.h中尽量少的引入其他的头文件，这样可以增强duilib的可移植性。

**Comment by mindfocus** [comment]
此话怎讲？移除.h也解决不了这个是WIN32 API的事实啊

**Comment by wangchyz** [comment]
以后在跨平台版本（如果有）改进
