### ISSUE TITLE
2.0分支里背景颜色bkcolor不起作用

### ISSUE THREAD

**Issue by Nokecy** [duilib/duilib#25]
bkcolor="0xff2872d5"
这样出现的是全黑背景。

**Comment by daviyang35** [comment]
2.0属于测试开发分支，主要做一些技术性的预研
目前主要停滞在两个问题上
1.Render的接口设计与分离
2.是否需要引入类似引用计数的功能来管理图片等资源
目前一些特性已经经过确认比较实用，可以自己合并到本地工程
但是2.0目前还不具备正式使用的条件
