### ISSUE TITLE
DuiDesigner工程编译不过，TRelativePosUI定义缺失

### ISSUE THREAD

**Issue by shantj** [duilib/duilib#28]
哥们能否帮忙优先解决一下啊，辛苦啦，谢谢啊

**Comment by denghongcai** [comment]
#10

**Comment by hoozh** [comment]
设计器不好用，还是手写准确

**Comment by coderev** [comment]
dui designer的工程在哪里？

**Comment by hoozh** [comment]
@coderev 删除了，之前的版本里能找到

https://github.com/duilib/duilib/commit/4fd0f956bf85e0fc79130f7cca91319e9ee995c7
