### ISSUE TITLE
字体设置无效

### ISSUE THREAD

**Issue by hoozh** [duilib/duilib#29]
以下代码字体设置没有效果了

default.xml 片段

    <DefaultConfig>
	<Font name="微软雅黑" size="12"/>
        <Font name="微软雅黑" size="12" bold="true"/>
        <Font name="微软雅黑" size="13" bold="true" />
        <Font name="微软雅黑" size="16"/>
        <Font name="微软雅黑" size="22"/>
    </DefaultConfig>

mainwnd.xml 片段

    <Label text="项目设置" textcolor="#FF136DEC" font="1"/>

**Comment by wangchyz** [comment]
现在font必须手动设置id，以前是默认设置的
比如<Font id="2" name="微软雅黑" size="12" bold="true"/>

**Comment by hoozh** [comment]
这样比默认设置好，方便改动字体设置，非常感谢！
