### ISSUE TITLE
CSliderUI::SetEnabled(false) 后，滑块依然能够拖动

### ISSUE THREAD

**Issue by hoozh** [duilib/duilib#33]
如题

用TestApp Demo试过，代码方式和 xml 方式都有问题

**Comment by hoozh** [comment]
发现是没判断 m_bEnabled 导致的

但是CControlUI 又有 m_uButtonState，可设 UISTATE_DISABLED 位，这样的话跟 m_bEnabled 不是重复了吗？

**Comment by wangchyz** [comment]
确实有这个bug，是UIEVENT_BUTTONUP消息处理不当导致，下次更新修复
