### ISSUE TITLE
请问UIButton控件中，有没有类似 hotimage的hotbkcolor属性？

### ISSUE THREAD

**Issue by banyudu** [duilib/duilib#35]
现在的代码中看不到。我想知道不使用hotimage的话，如何在鼠标悬停在按钮上面时修改按钮的背景色。

**Comment by wangchyz** [comment]
有hotbkcolor

**Comment by SevenWow** [comment]
@wangchyz 建议再加一个pushedbkcolor对应pushedbkimage。我觉得这个应用挺多的
