### ISSUE TITLE
DuiLib中异步Notify的实现bug

### ISSUE THREAD

**Issue by langxiong** [duilib/duilib#36]
异步Notify的消息响应现有实现是在CPaintManagerUI::MessageHandler入口和结尾添加，
任何Windows消息的响应都会触发消息检索
当响应异步Notify的代码调用了DoModal时， 会触发异常

可简单修改， 在添加异步Notify时， 通过
        TNotifyUI *pMsg = new TNotifyUI;
        pMsg->pSender = Msg.pSender;
        pMsg->sType = Msg.sType;
        pMsg->wParam = Msg.wParam;
        pMsg->lParam = Msg.lParam;
        pMsg->ptMouse = Msg.ptMouse;
        pMsg->dwTimestamp = Msg.dwTimestamp;
         m_aAsyncNotify.Add(pMsg);
	::PostMessage(m_hWndPaint, WM_USER_DUILIB_ASYNC_NOTIFY, NULL, NULL);
并在MessageHandle中响应对应的消息

**Comment by ml232528** [comment]
兄弟，和我的做法一样哈。不过m_aAsyncNotify链表需要加锁。不然多线程调用SendNotify会出问题。

**Comment by wangchyz** [comment]
可否直接提交patch，我来合并

**Comment by wangchyz** [comment]
已修改
