### ISSUE TITLE
容器滚动条的问题

### ISSUE THREAD

**Issue by heiyun1270** [duilib/duilib#38]
因为不知道是不是刻意为之所以这里只说是问题，而不是BUG。
现象：
HorizontalLayout 开启垂直滚动条无用，不显示
VerticalLayout 开启水平滚动条有显示，但范围不对
Container 开启滚动条无效，SetPos中没有执行ProcessScrollBar

个人意见，不同容器应该只是布局方式不同，而与滚动条无关。所有容器的双向滚动条都应该正确支持，由用户开关。这样更方便灵活。

**Comment by wangchyz** [comment]
1、HorizontalLayout 开启垂直滚动条无用，不显示
  这个问题估计是因为HorizontalLayout会默认把子控件拉到和自己高度一样，所以也不需要滚动条，设置子控件的minwidth或者float="true"估计就可以看到了
2、VerticalLayout的水平滚动条计算比较复杂，所以做了简化处理，把范围设置工作交给用户
3、Container只是一个透明容器，一般不做显示用，如果不是对库很熟悉，还是少用

**Comment by heiyun1270** [comment]
HorizontalLayout 试过设置minwidth没效果，float="true"就不受滚动条控制了
原有的需求是：
窗口更改大小，各容器自适应缩放，中间有一部份内容因为不能缩放，当窗口缩放够小后，那部份的父容器显示水平和垂直滚动条来显示所有内容，但发现各个容器除了List外其它容器都不能实现这个功能。
虽然功能最后是可以实现，但是用List实在容易造成误解。从我的角度来讲更希望用Container容器，因为这样可以很好的说明容器中的内容应是唯一或互相覆盖。好吧，我承认其实是我强迫症犯了，用List确实不爽，最后自己继承Container自定义了个容器。

**Comment by heiyun1270** [comment]
最后在补充一点儿，上面说的功能用List还是会有小BUG，就是在窗口改变大小时，滚动条范围发生变化时，List中的图会抖动。
测试用的代码：
<List hscrollbar="true" vscrollbar="true">
              <Control width="1920" minwidth="1920" height="1080" minheight="1080" bkimage="test.gif" />   </List>

**Comment by wangchyz** [comment]
哦，我看了一下HorizontalLayout的代码，确实是没有vscrollbar的计算，所以设置minheight是没用的
你说的问题，可以这样解决
在xml中：
<VerticalLayout float="true" width="200" height="200" bkcolor="#FFFF00FF" vscrollbar="true" hscrollbar="true">
  <Control name="TEST" width="600" minwidth="600" minheight="600" bkimage="button_over.bmp"/>
</VerticalLayout>
在窗体的初始化代码中：
		CControlUI* pControl = m_pm.FindControl(_T("TEST"));
		if (pControl) {
			CVerticalLayoutUI* pParent = static_cast<CVerticalLayoutUI*>(pControl->GetParent());
			pParent->GetHorizontalScrollBar()->SetScrollRange(410); //加上滚动条宽度
		}
