### ISSUE TITLE
新版本设置字体不起作用

### ISSUE THREAD

**Issue by wxr-vbox** [duilib/duilib#42]
测试了360的demo，里面设置的字体不起作用。

**Comment by wxr-vbox** [comment]
![1](https://cloud.githubusercontent.com/assets/16031886/11421880/5c1e344a-9472-11e5-93a9-107b7d2b2649.png)
![2](https://cloud.githubusercontent.com/assets/16031886/11421879/5c1c19e4-9472-11e5-8769-5b7a96049d14.png)
![3](https://cloud.githubusercontent.com/assets/16031886/11421881/5c1e63b6-9472-11e5-8955-9c399a9c6918.png)

**Comment by wangchyz** [comment]
最新版本的duilib要求在xml中字体指定id，已经修复demo资源

如：
 <Font id="0" name="宋体" size="13" bold="false"/>
 <Font id="1" name="宋体" size="12"/>
