### ISSUE TITLE
RichEdit 字体粗细和倾斜属性设置无效

### ISSUE THREAD

**Issue by lion117** [duilib/duilib#43]
#问题一
在使用duilib 最新版的库中, 使用RichEdit 控件设置字体的时候, 字体大小和字体类型能够工作正常. 但是
**字体粗细** 和**字体倾斜** 两个属性就存在以下问题：
- 首次设置倾斜和粗细有效
- 取消粗细或倾斜, 无效

RichEdit 设置完粗细和倾斜之后, 就无法清除了. 
#问题二
另外颜色设置接口也存在颜色错乱的问题

**Comment by wangchyz** [comment]
已修复，另外颜色错乱是什么情况呀
注意duilib中使用的颜色是个DWORD值，从高位到低位，每两位一组，依次是ARGB，和Windows系统中定义的RGB类型是不一样的

**Comment by lion117** [comment]
原来如此, 因为我采用的windows版本的 DWORD 值, 所以并未对数值进行处理, 所以用字体对话框选中后的颜色值直接传进Richedit控件中去设置颜色, 设定的颜色值和实际值多数情况下并不一致.
