### ISSUE TITLE
CDelegateBase::equal问题

### ISSUE THREAD

**Issue by nustxujun** [duilib/duilib#45]
template <class O, class T>
class CDelegate : public CDelegateBase的实现写的有问题

实际equal的时候，比较的是CDelegateBase的m_pFn,而 CDelegateBase的m_pFn则是一个形参的栈地址，传入的时候之前是这么写的CDelegate(O* pObj, Fn pFn) : CDelegateBase(pObj, &pFn)

我猜之前写这块的人不知道怎么转换指针类型，所以写的这么别扭
我自己修改的实现
template <class O, class T>
class CDelegate : public CDelegateBase
{
    typedef bool (T::* Fn)(void*);
public:
    CDelegate(O* pObj, Fn pFn) : CDelegateBase(pObj, *(void**)&pFn) { }
    CDelegate(const CDelegate& rhs) : CDelegateBase(rhs) {  } 
    virtual CDelegateBase* Copy() const { return new CDelegate(*this); }

protected:
    virtual bool Invoke(void* param)
    {
        O* pObject = (O*) GetObject();
		union
		{
			void* ptr;
			Fn fn;
		}func = { GetFn() };
		return (pObject->*func.fn)(param);
    }  

};

**Comment by wangchyz** [comment]
没看懂，可以给一个出错的测试代码吗

**Comment by nustxujun** [comment]
CEventSource e += MakeDelegate(Object, Function);
e -= MakeDelegate(Object,Function); <-----永远失败

**Comment by wangchyz** [comment]
我测试过是可以的呀
在TestApp1的例子中
在
        if( pSilder ) pSilder->OnNotify += MakeDelegate(this, &CFrameWindowWnd::OnAlphaChanged);
后面增加一句
	if( pSilder ) pSilder->OnNotify -= MakeDelegate(this, &CFrameWindowWnd::OnAlphaChanged);
调试进去是成功的

你说的是哪种情况？

**Comment by nustxujun** [comment]
那只是因为那个形参的栈地址刚好都一样，你仔细看onPrepare里几个MakeDelegate出来的mFn地址都是一样的
你把if( pSilder ) pSilder->OnNotify -= MakeDelegate(this, &CFrameWindowWnd::OnAlphaChanged);
放onPrepare外面就会发现根本没用

**Comment by wangchyz** [comment]
谢谢，已经修正
另外提一下，贴代码要用makedown格式才行，不然贴出来乱的，看了好久没看明白
https://guides.github.com/features/mastering-markdown/

    ```
    if (isAwesome){
      return true
    }
    ```
