### ISSUE TITLE
Slider 控件绘制渲染上的小瑕疵

### ISSUE THREAD

**Issue by lion117** [duilib/duilib#47]
seeing is believing 
![q -20151203103716](https://cloud.githubusercontent.com/assets/3996029/11550356/64147f64-99aa-11e5-9d59-aa1b390f06f5.png)
> **Slider 控件的边缘处, 由于直接使用矩形绘制, 当圆型滑块滑至边缘处, 将导致两尖角突出**. 如上图所示

当然采用方形滑块, 不存在这样的问题. 但方形滑块用的真的很少. 圆形才是主流啊, 这导致在后期需要美工用P图欺骗的方式来处理这类型的瑕疵.

**Comment by wangchyz** [comment]
滑槽不能圆角吗，或者滑槽两端图片适当短一点，这个似乎不是库应该解决的问题

**Comment by progmboy** [comment]
其实这个改起来很简单。。给Slider 控件加一个padding值。 padding值这可以自定义设置。绘制矩形的时候减去padding就好了嘛

**Comment by wangchyz** [comment]
设置贴图dest也可以的吧

**Comment by progmboy** [comment]
我记得试过这个方法。。当时貌似是效果不好所以自己加了个padding,原因记不清了
