### ISSUE TITLE
关于带有阴影的PNG作为背景时不会有透明效果了

### ISSUE THREAD

**Issue by ying32** [duilib/duilib#48]
之前使用的版本中可以使用SetBackgroundTransparent，现在用您的新版本后发现没有这个方法了
然后PNG带有阴影的就会成为黑边。新的代码中看到Layout相关的，还没有怎么明白怎么使用，
SetLayout为True后貌似就什么都不显示了。

**Comment by wangchyz** [comment]
现在已经支持，用法就是设置layeredimage就行了
