### ISSUE TITLE
不知道这个算BUG还是作者您有其它意义

### ISSUE THREAD

**Issue by ying32** [duilib/duilib#50]
无法响应DUI的menu消息了，仔细看了下代码发现UIManager.cpp的WM_CONTEXTMENU中增加了一句if( IsCaptured() ) break;
在WM_RBUTTONDOWN中看到有SetCapture()，此时鼠标抬起首先收到WM_CONTEXTMENU消息，这时IsCaptured等于true, 就没有响应了。

**Comment by wangchyz** [comment]
这是一个bug，原来版本是没有RBUTTONDOWN处理的，估计是哪位提供patch的时候加上的，然后WM_CONTEXTMENU冲突了，你可以直接把SetCapture()删掉试试，下次更新也会这么改，如果有问题请留言。

duilib设计的时候已经考虑了触摸平台的体验，默认情况下已经不建议使用处理右键和水平滚动条。
