### ISSUE TITLE
请问下duilibDesigner应该使用哪个？

### ISSUE THREAD

**Issue by RainyBlueSky** [duilib/duilib#55]

**Comment by ihaibara** [comment]
这东西短时间内已经不存在了，还是老老实实自己用xml文件写吧。~( ﹁ ﹁ ) ~~~

**Comment by heiyun1270** [comment]
我写了一个，勉强能用，最近忙没空去搞重构和优化,地址:
http://blog.csdn.net/tony_zn/article/details/50298089

**Comment by ml232528** [comment]
https://github.com/CodeBees/duilib-Ex-Debug
这个里面那个勉强能用。
