### ISSUE TITLE
SetFloat之后，SetFixedXY，SetFixedWidth之类的函数调用都没有用。

### ISSUE THREAD

**Issue by ml232528** [duilib/duilib#56]
SetFixedXY的代码：
void CControlUI::SetFixedXY(SIZE szXY)
{
    m_cXY.cx = szXY.cx;
    m_cXY.cy = szXY.cy;
    if( !m_bFloat ) NeedParentUpdate();
    else NeedUpdate();
}
如果m_bFloat被设置父控件没有更新。NeedUpdate只会导致控件自己的SetPos被调用。
bool CPaintManagerUI::MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, LRESULT& lRes)
{
...
pControl->SetPos(pControl->GetRelativePos(), true);
...
}
然后控件SetPos代码导致SetFixedXY调用无效，m_cXY被还原：
void CControlUI::SetPos(RECT rc, bool bNeedInvalidate)
{
...
if( m_bFloat ) {
		CControlUI* pParent = GetParent();
		if( pParent != NULL ) {
			...
			m_cXY.cx = rc.left - rcPercent.left;
			m_cXY.cy = rc.top - rcPercent.top;
			...
		}
	}
...
}

最后SetFixedXY调用什么都不会发生。

**Comment by wangchyz** [comment]
是有问题，简单修复了一下，如果有问题麻烦再回复一下
