### ISSUE TITLE
控件背景黑色问题

### ISSUE THREAD

**Issue by horatii** [duilib/duilib#60]
edit控件在透明下背景为黑色，其他控件在不贴图纯色带alpha的情况下背景黑色

**Comment by k1988** [comment]
本司用的ui库是基于duilib改了好几年的，之前在我们的库里改进过一次，不知道是不是和这个问题类似。
我们的问题是，在透明窗口中，richedit是使用m_pTwh->GetTextServices()->TxDraw来画的，绘制后alpha通道为0，所以就显示不出来。
后来加了个判断，如果是透明窗口，则先绘制在一个缓存的dc上，在绘制前将所有区域的alpha通道设置成特殊值， 绘制后把特殊值还存在的设置成透明，为0的设置成不透明，再alphablend到正式dc上。
