### ISSUE TITLE
在设置过layeredopacity熟悉后所有自控件背景黑色

### ISSUE THREAD

**Issue by horatii** [duilib/duilib#61]
在设置过layeredopacity熟悉后，当背景为带alpha的纯色，控件响应鼠标事件有黑色背景，如 CButtonUI控件

**Comment by horatii** [comment]
不设置layeredopacity也有这个情况

**Comment by wangchyz** [comment]
不设置layeredimage，使用带alpha的纯色或图片作为背景，出现这种情况是正常的，也是应该避免的
