### ISSUE TITLE
opacity与layeredopacity代码重合

### ISSUE THREAD

**Issue by horatii** [duilib/duilib#62]
layeredopacity属性似乎是多余，在配置文件中设置对窗口没有起什么作用
，还有希望提供一个关于 LayeredImage 的 demo出来

**Comment by wangchyz** [comment]
layeredopacity需要配合LayeredImage 一起用才行
LayeredImage 的使用只需要设置一张带alpha的图片，运行一下就明白了

**Comment by wangchyz** [comment]
layeredopacity需要配合LayeredImage 一起用才行
LayeredImage 的使用只需要设置一张带alpha的图片，运行一下就明白了
