### ISSUE TITLE
控件布局bug

### ISSUE THREAD

**Issue by horatii** [duilib/duilib#66]
<VerticalLayout bkcolor="#FFFFFFFF">
                <Control />
                <InputControl visible="false" height="25" name="input_control" font="0" />
                <NewsScrollBar height="25" name="news_scroll_bar" bkcolor="#FFFF0000"/>
                <Control />
            </VerticalLayout>

控件一个显示另外一个隐藏bug，第二个控件的位置不能正确显示

**Comment by wangchyz** [comment]
我试了，没发现问题呀

```
<?xml version="1.0" encoding="UTF-8"?>
<Window mininfo="200,360" size="360,600">
	<VerticalLayout bkcolor="#FFEFEFEF" >
        <Control />
        <Control visible="false" height="25" bkcolor="#FF6F0000" />
        <Control height="25" bkcolor="#FFFF006F"/>
        <Control />
	</VerticalLayout>
</Window>
```
你把这个保存成test1.xml放到bin目录下试试，有问题请回复

**Comment by horatii** [comment]
我的问题，自定义控件没有处理好！不好意思，顺便问一下那个layeredimage是不是没有实现好，我在我这里设置了好多次都不行，都快没有自信了。希望能在demo里增加一个关于layeredimage的demo
