### ISSUE TITLE
webbrowser内核问题

### ISSUE THREAD

**Issue by EganLi** [duilib/duilib#69]
webbrowser控件可以修改内核吗？使用webkit内核

**Comment by wangchyz** [comment]
你要的是双核技术，还是duilib使用webkit的功能？
duilib使用webkit还是比较简单的，可以嵌入wke或者libcef，你网上找一下相关代码

**Comment by EganLi** [comment]
只需要duilib使用webkit即可。
我在网上找过代码，在以前的duilib上能用，但是现在不行了……

**Comment by wangchyz** [comment]
调试一下看看，估计有小地方需要改动一下把
