### ISSUE TITLE
异形透明窗口功能失效

### ISSUE THREAD

**Issue by shantj** [duilib/duilib#70]
比如一个verticalLayout，不设置背景颜色和图片，以前默认是透明的，现在变成黑屏了

**Comment by wangchyz** [comment]
麻烦描述的详细点

**Comment by shantj** [comment]
@wangchyz  不好意思刚看到，举个例子，比如说RichListDemo
把 skin\RichListRes\duilib.xml 这个文件的第八行
`<VerticalLayout name="" text="" tooltip="" float="false" bordersize="0" bkcolor="#00000000" bkcolor2="#00000000" bordercolor="#006B93B2" inset="5,0,5,1" bkimage="file='main.png' corner='13,85,12,34'">`
改成
`<VerticalLayout >` 

老版本：标题栏应该是透明
新版本：标题栏变成了黑色

但是我不知道从哪个版本开始出现的问题，我用的是15年7月份的版本...

**Comment by shantj** [comment]
我用15年7月份版本是会透明的，但是最新的版本，变成了黑色

**Comment by wangchyz** [comment]
黑色是正常的
除非是layered窗口，不然怎么透明呀

**Comment by shantj** [comment]
但是我窗体设置layeredimage之后，整个窗口都透明了，但是我只是想那个标题栏透明。
麻烦指导一下，我该怎么设置？  谢谢了

**Comment by redrains** [comment]
即使只想让窗体一部分是透明的，那也需要开启layered窗口，然后让你的背景图的标题栏部分是透明的就可以了
