### ISSUE TITLE
padding属性和List控件

### ISSUE THREAD

**Issue by SevenWow** [duilib/duilib#82]
1、padding属性在某些大多数情况下有问题，一般是右、下有问题，padding变得非常大，是很严重的BUG。

2、List控件的SelectItem在某些情况下无效，即选中不了。比如在切换tab后用代码就选中不了了。

3、此外，友好性建议，建议支持VS2008编译平台，因为做VC开发的大部分使用08平台。

@wangchyz 

去年的老版本没有这样的问题。

**Comment by SevenWow** [comment]
![Uploading test1 - 副本.png…]()

**Comment by wangchyz** [comment]
扔一个不含图片的xml上来看看呀
vs2008是支持的，只是要自己转换一下工程

**Comment by SevenWow** [comment]
@wangchyz 我想上传测试的Demo来着，但是这网站死活上传失败（PNG图片都失败...），我发你gmail邮箱吧，你查收一下。

**Comment by SevenWow** [comment]
关于padding的问题，附件为DEMO，内含XML。
由于上传ZIP被gmail阻止，我改了后缀，你把后缀改为ZIP吧。

2016-05-05 20:29 GMT+08:00 wangchyz <notifications@github.com>:

**Comment by wangchyz** [comment]
已修复
