### ISSUE TITLE
【求助】请问哪位大牛维护的Duilib还是VS2008版的。

### ISSUE THREAD

**Issue by BestRiventoo** [duilib/duilib#83]
请问哪位大牛维护的Duilib还是VS2008版的。请发邮箱592902419@qq.com。小弟不胜感激。谢谢！！！

**Comment by kuafuwang** [comment]
国内的人怎么这么保守，现在都有2015了，项目起码也得用2010吧。

**Comment by kuafuwang** [comment]
国内的人怎么这么保守，现在都有2015了，项目起码也得用2010吧。

**Comment by BestRiventoo** [comment]
是啊   我用的就是2010  可是2010也打不开2013版的  所以求一下2008的

**Comment by JackLongBow** [comment]
不同版本之间的转换并不难吧？有工具，还可以手动修改啊。

**Comment by wangchyz** [comment]
本来就是2008升上来的，你找下历史版本的工程文件或者自己建一个工程把文件加进去
