### ISSUE TITLE
自绘标题栏bug，无法捕获鼠标单击事件

### ISSUE THREAD

**Issue by damonxx** [duilib/duilib#86]
屏蔽系统标题栏，自绘标题栏后无法响应click事件，即最小化、最大化、关闭按钮无效，
双击标题栏还是可以还原和放大，
使用之前的duilib库时一切正常

**Comment by wangchyz** [comment]
https://github.com/duilib/duilib/commit/02d1ed8832a14764a00d0e50c0bc08033883051f
