### ISSUE TITLE
关于新版本duilib自绘控件的问题

### ISSUE THREAD

**Issue by damonxx** [duilib/duilib#88]
继承自CControlUI类的自定义控件类，获取句柄m_hWnd正常，将一个位图attach给这个控件句柄时，位图始终无法显示，可以确定自绘控件已经加载显示
但是从网上找到的一个2011年版本的duilib库，却可以正常显示。

**Comment by wangchyz** [comment]
自定义控件类有自己的Windows窗口吗？

**Comment by damonxx** [comment]
自定义控件是绘在duilib 窗口的，xml中加载一个自定义控件wnd，重写CreateControl函数中调用CreateWindow创建一个句柄也还是attch 不上

**Comment by wangchyz** [comment]
建议你去google一下duilib下wke控件的封装，有窗口和无窗口两种模式的，可以参考一下
