### ISSUE TITLE
建议duilib提供webkit + nativeapp的解决方案

### ISSUE THREAD

**Issue by lion117** [duilib/duilib#89]
Duilib提供的MVC架构,让C++ 的界面编程变得非常简单轻松. 
但是现在的应用都不再是一个孤立的app,单纯的本地功能已经远远无法满足需求.

本地应用+webkit 的组合模式已经成为一种主流趋势
本地应用胜在实时性和效率上,对于本地文件操作和高性能显示依旧具备优势
web则胜在大数据量的处理和高度灵活的复杂界面处理.

虽然知道duilib提供 activeX 这类插件, 但是IE 的渲染性能和对HTML5的支持已经远无法达到要求.

强烈建议duilib能够提供 cef这类巨无霸的支持. 本地应用开发更加简单

**Comment by CodeBees** [comment]
https://github.com/CodeBees/CEFWebkitBrowser

**Comment by lostcoder0812** [comment]
加cef就太巨大了，完全没有意思，不符合duilib的设计理念。
网上的cef控件实现应该不少，找一些自己整合吧。
