### ISSUE TITLE
可否做一个关于splitimage属性的Demo，或者给点代码|Can do a Demo on the properties of splitimage, or to point code

### ISSUE THREAD

**Issue by zbooa** [duilib/duilib#91]
想知道splitimage属性是怎么用的。| Want to know how the splitimage attribute is used.

**Comment by wangchyz** [comment]
哪个控件有这个属性？

**Comment by zbooa** [comment]
@wangchyz 只要是图片都有这个属性。
加上属性 splitimage="true"则说明此图片需要被分成四个部分显示。规定图片的四个部分依次按normalimage、hotimage、pushedimage、focusimage排列，程序就自动计算每个图片的位置，就无需在XML填写source位置。
我是不会如何设置它的状态，就是只能得到一个状态，图片始终不变。。

**Comment by wangchyz** [comment]
按钮有个属性是fivestatusimage，直接设置图片，会按从左到右均匀分成5个小图片分别对应按钮的五种状态。
官方duilib版本没有splitimage这个属性，你检查一下你用的是谁的版本，直接向他本人咨询吧

**Comment by zbooa** [comment]
@wangchyz 你是从哪里知道这些属性的？在网上都没找到啊。不过你说的确是对的，我的版本不一样，现在我用官方版本了。
